### ISSUE TITLE
Use subcommands on the CLI

### ISSUE THREAD

**Issue by hangtwenty** [ajk8/fencepy#12]
`fencepy -a` should be `fencepy activate`, and so on.

CLIs have trended towards using subcommands where appropriate. A well-known example is `git` -- `git status`, `git push`, `git pull`. Another example is `gradle` -- `gradle assemble`, `gradle upload`, etc. It's common to other "development task" CLIs beyond `gradle`, such as `pip` -- `pip install`, etc -- Grunt.js, etc. `vagrant`, `docker`, `ansible`...

It's good to be consistent with other tools that developers like to use. If developers don't like the interface, they might pass on the whole tool.

More concrete benefits to usability:
* a full word is less ambiguous and easier to remember than a single letter
* it is unambiguous that subcommands aren't mutually compatible with each other. When options and flags are used for everything, it can become complicated to distinguish which items are mutually exclusive

**Comment by hangtwenty** [comment]
I'll do a pull request on this using docopt if you gimme a week :palm_tree:

**Comment by ajk8** [comment]
Sounds great!

**Comment by ajk8** [comment]
Found some time last night and took care of this.

**Comment by hangtwenty** [comment]
great! :+1:
